### ISSUE TITLE
getOrderBuyerInfo(): Error: Undefined index: query

### ISSUE THREAD

**Issue by MST1122** [double-break/spapi-php#1]
please update this condition in Client.php.

if ($requestOptions['query']) {
     ...
}

to

if (isset($requestOptions['query'])) {
     ...
}

**Comment by lyubo-slavilov** [comment]
Ok, I will. But you can do Pull Requests, you know :)
Does it cause any failures?

**Comment by lyubo-slavilov** [comment]
fix released as v1.0.2
