### ISSUE TITLE
The data returned by getreportDocument after downloading and decompression is garbled 

### ISSUE THREAD

**Issue by ykw090721** [double-break/spapi-php#11]
After I call ASECryptoStream::decrypt to decrypt the data, the returned data is garbled. I tried gzip decompression and conversion of the encoding type, but it can’t solve this problem. Have you encountered this problem?

**Comment by lyubo-slavilov** [comment]
@ykw090721, please provide example code which describes your use case at best.
@MST1122 can you look at this?

**Comment by ykw090721** [comment]
`$result=$reportApi->getReport($param['reportId']);
            if(isset($result['payload'])){
               $payLoadData=$result['payload'];
               if($payLoadData['processingStatus']=='DONE'){
                   $re=$reportApi->getReportDocument($payLoadData['reportDocumentId']);
                   $payload=$re['payload'];
                  $compressionAlgorithm=$payload['compressionAlgorithm'];
                   $encryptionDetails=$payload['encryptionDetails'];
                   $key=base64_decode($encryptionDetails['key'],true);
                   $initializationVector=base64_decode($encryptionDetails['initializationVector'],true);
                   $url=$payload['url'];
                   $decryptedFile = ASECryptoStreamFactory::decrypt(curl_get($url), $key, $initializationVector);
                   file_put_contents('a.txt','aaa='.$decryptedFile.PHP_EOL,FILE_APPEND);
                   $decryptedFile = preg_replace('/\s+/S', " ", $decryptedFile);
                   file_put_contents('a.txt','xml='.$decryptedFile.PHP_EOL,FILE_APPEND);
        
               }
            }`
@lyubo-slavilov When downloading data, I tried to use file_get_contents and curl to obtain the data, and use the PHP decompression function gzdecode or gzinflate. The data obtained at the end is garbled, and I don’t know how to deal with it.

**Comment by ykw090721** [comment]
The problem is solved, I just call gzdecode after decrypting the data, but it didn’t work before

**Comment by ykw090721** [comment]
> 问题解决了，我只是在解密数据后调用gzdecode，但是之前没有用

` public function downloadFeedProcessingReport($payload)
    {
        $encryptionDetails = $payload['encryptionDetails'];
        $feedDownloadUrl = $payload['url'];
        $key = $encryptionDetails['key'];
        $initializationVector = $encryptionDetails['initializationVector'];

        // base64 decode before using in encryption
        $initializationVector = base64_decode($initializationVector, true);
        $key = base64_decode($key, true);
        $decryptedFile = ASECryptoStream::decrypt(file_get_contents($feedDownloadUrl), $key, $initializationVector);
        if($payload['compressionAlgorithm']=='GZIP') {
            $decryptedFile=gzdecode($decryptedFile);
        }
        $decryptedFile = preg_replace('/\s+/S', " ", $decryptedFile);
        $xml = simplexml_load_string($decryptedFile);
        $json = json_encode($xml);
        return json_decode($json, TRUE);
    }`
Should be this
