### ISSUE TITLE
Pricing Operation - The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by cesarelasorella** [double-break/spapi-php#13]
Hi @lyubo-slavilov,
sorry for delay.
I tried to add this change (#6 ) but nothing new. The same error occurs.
The code used for the call is the following:

```
//Create SP API ProductPricing client and execute one ot its REST methds.
  $pricingClient = new DoubleBreak\Spapi\Api\ProductPricing($cred, $config);
  $result = $pricingClient->getPricing([
    'MarketplaceIds' => "APJ6JRA9NG5V4",
	'ItemType' => "Sku",
	'Skus' => ["5901721606210"]
  ])['payload'];
```

I'm trying to get price for SKU 5901721606210 on Italy Marketplace.

Thank you

**Comment by lyubo-slavilov** [comment]
Your Skus parameter should be coma separated string instead of an array, I
think.

**Comment by lyubo-slavilov** [comment]
May be something like:
Something like:
```php
$pricingClient = new DoubleBreak\Spapi\Api\ProductPricing($cred, $config);
  $result = $pricingClient->getPricing([
    'MarketplaceIds' => "APJ6JRA9NG5V4",
	'ItemType' => "Sku",
	'Skus' => "5901721606210"
  ])['payload'];
 ```
 If you need more than one Sku:
 ```php
 $pricingClient = new DoubleBreak\Spapi\Api\ProductPricing($cred, $config);
  $result = $pricingClient->getPricing([
    'MarketplaceIds' => "APJ6JRA9NG5V4",
	'ItemType' => "Sku",
	'Skus' => "5901721606210,0126061271059,.."
  ])['payload'];
```

**Comment by cesarelasorella** [comment]
Thank you @lyubo-slavilov, changing Skus as you suggest seems something change because the error is now different:

_`403 Forbidden` response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...)_

About credentials and configurations I followed the [official guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application)
I have a doubt; do you know if selling-partner api works fine on Italy MP? I think to read somewhere that at moment this service works only in the US MP.

**Comment by lyubo-slavilov** [comment]
@cesarelasorella Hello,
> I have a doubt; do you know if selling-partner api works fine on Italy MP? I think to read somewhere that at moment this service works only in the US MP

Unfortunately I am far from being Amazon SP API expert. I just was able to figure out how to stratify their request signing routine. So, I cant really tell. I am personally having access troubles with some other endpoints for DE market... So, we are all waiting for AMZ support to reply, I guess.

I am going to close the issue since it is not related to the code itself 😔
