### ISSUE TITLE
Get inventory overview request

### ISSUE THREAD

**Issue by bastiaansenglenn** [double-break/spapi-php#2]
Hello,

First of all, great package! It helped me a lot in some cases. 

I would like to get an overview of my offers inventory (non FBA offers) under my account. Is there a model that you can use for that?
Maybe I am overlooking something!

I tried Feeds and Reports now, but when i'm trying to post something I get the following errors;
```
$reportClient = new Reports($cred, $config);
$result       = $reportClient->createReport([
     'reportType'     => 'GET_MERCHANT_LISTINGS_DATA',
     'marketplaceIds' => 'A1PA6795UKMFR9',
]);
```

`{\n
  "errors": [\n
    {\n
      "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n
\n
The Canonical String for this request should have been:\n`

I hope you can help me! If i need to provide more details, I would like to hear it too.

Thank you in advance!

**Comment by lyubo-slavilov** [comment]
@bastiaansenglenn It smells as Signer issue. I'll check it and get back as soon as possible

**Comment by lyubo-slavilov** [comment]
@bastiaansenglenn Problem solved.
There was a problem in the `Signer` class. It boils down to failed variable name refactoring.
Also there was a bit of confusion in what order payload keys were evaluated during the sign process. Now it is fixed.

New composer package version released: **v1.0.3.**
Please do `composer update double-break\spapi-php`

Cheers!

**Comment by lyubo-slavilov** [comment]
> I would like to get an overview of my offers inventory (non FBA offers) under my account. Is there a model that you can use for that?
> Maybe I am overlooking something!

@bastiaansenglenn About that - You is as infromed as I am.
Try inventory or smth (`FbaInventory` client). I am still figthing the Orders model :) 

Unfortunately my support on this may only extend to inner workings of the client. I can't offer API application logic support

**Comment by bastiaansenglenn** [comment]
Hello,

Thanks for your help, it helped! However, I now run into another error in the same request. 
I'm just not sure if it's also a SIGN bug.

I'm no longer getting the signature difference error, but i got the following error;
```
{​\n
  "errors": [\n
    {​\n
      "code": "InvalidInput",\n
      "message": "Report rejected for this client. your report could not be applied to any marketplaces",\n
      "details": ""\n
    }​\n
  ]\n
}
```

Have you experienced the same problem with your request, or is this something within my account?

Thanks in advance!
