### ISSUE TITLE
403 Forbidden on createFeedDocument

### ISSUE THREAD

**Issue by moslemparve** [double-break/spapi-php#27]
aws-tokens is generating successfully means i am authentication from aws but when i call  createFeedDocument method it is giving following error can any one help what i am doing wrong.?
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: ``Client error: `POST https://sellingpartnerapi-fe.amazon.com/feeds/2020-09-04/documents` resulted in a `403 Forbidden` response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...)``

**Comment by fossman83** [comment]
I have the same issue, did you manage to figure out what the issue was?

**Comment by yao657355700** [comment]
I have the same issue, did you manage to figure out what the issue was?

**Comment by pradeepKsrvastva** [comment]
@fossman83 @moslemparve Guys did you figured this out i am having same issue
