### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by MST1122** [double-break/spapi-php#3]
Hi there,

when i call createFeedDocument() function get this error response:
 
Client error: `POST https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/documents` resulted in a `403 Forbidden` response: { "errors": [ { "message": "The request signature we calculated does not match the signature you provided. C (truncated...)

my code for this request:

$feedClient = new Feeds($cred, $config);
$result = $feedClient->createFeedDocument(["contentType" => "text/tab-separated-values; charset=UTF-8"]);

Credentials and config are correct because when I call the GetOrders function with the same parameters, I get a successful response.

**Comment by kingsun-he** [comment]
Hi MST1122, I met the same problem. How do you resolve this problem?
