### ISSUE TITLE
How do we download feed submission report?

### ISSUE THREAD

**Issue by aniruddhaad** [double-break/spapi-php#34]
(new \DoubleBreak\Spapi\Helper\Feeder())->downloadFeedProcessingReport($payload); gives us only feed processing status.

How do we download the actual feed submission report?

**Comment by bastiaansenglenn** [comment]
@aniruddhaad i think you should use the `getFeedDocument($feedDocumentId)` method from the [Feeds](https://github.com/double-break/spapi-php/blob/master/src/Api/Feeds.php) class. After your feed is processed you can retrieve it with the `getFeedDocument()` method.

**Comment by aniruddhaad** [comment]
> @aniruddhaad i think you should use the `getFeedDocument($feedDocumentId)` method from the [Feeds](https://github.com/double-break/spapi-php/blob/master/src/Api/Feeds.php) class. After your feed is processed you can retrieve it with the `getFeedDocument()` method.

Thank you for the reply @bastiaansenglenn. 

The src/helper/Feeder.php has only 1 method to download report and it only downloads feed status. I am already getting this as "Completed".

I think the Feeder.php file is missing one function which is explained in the amzn repo (https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-documents-helper-java). From code it seems that it actually downloads the feed report from amazon -

```

Download
import java.io.BufferedReader;
import java.io.IOException;
 
import com.amazon.spapi.documents.CompressionAlgorithm;
import com.amazon.spapi.documents.DownloadBundle;
import com.amazon.spapi.documents.DownloadHelper;
import com.amazon.spapi.documents.DownloadSpecification;
import com.amazon.spapi.documents.exception.CryptoException;
import com.amazon.spapi.documents.exception.HttpResponseException;
import com.amazon.spapi.documents.exception.MissingCharsetException;
import com.amazon.spapi.documents.impl.AESCryptoStreamFactory;
 
public class DownloadExample {
    final DownloadHelper downloadHelper = new DownloadHelper.Builder().build();
 
    public void downloadAndDecrypt(String key, String initializationVector, String url, String compressionAlgorithm) {
        AESCryptoStreamFactory aesCryptoStreamFactory =
                new AESCryptoStreamFactory.Builder(key, initializationVector).build();
 
        DownloadSpecification downloadSpec = new DownloadSpecification.Builder(aesCryptoStreamFactory, url)
                .withCompressionAlgorithm(CompressionAlgorithm.fromEquivalent(compressionAlgorithm))
                .build();
 
        try (DownloadBundle downloadBundle = downloadHelper.download(downloadSpec)) {
            // This example assumes that the downloaded document has a charset in the content type, e.g. 
            // text/plain; charset=UTF-8
            try (BufferedReader reader = downloadBundle.newBufferedReader()) {
                String line;
                do {
                    line = reader.readLine();
                    // Process the decrypted line.
                } while (line != null);
            }
        } catch (CryptoException | HttpResponseException | IOException | MissingCharsetException e) {
            // Handle exception here.
        }
    }
}
```
This is different from public function downloadFeedProcessingReport. Any idea how to generate this using the Java + Maven (I have asked this question in amzn repo as well but no reply yet https://github.com/amzn/selling-partner-api-models/issues/1505 )?

any idea/suggestions?

Thanks
