### ISSUE TITLE
upload feed

### ISSUE THREAD

**Issue by msgultekin** [double-break/spapi-php#4]
The response I got from the createfeeddocument function is initializationVector and key. but I can't find the upload function to use them. 

(https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md 
step 2)

**Comment by mustafa-bayindir** [comment]
Hello msgultekin im mustafa. i have the same problems as you stated probably we can help eachother. on my profile you can find my email to contact me if you're interessted

**Comment by ykw090721** [comment]
I have the same problem, how to encrypt the uploaded data and how to upload it

**Comment by lyubo-slavilov** [comment]
Hello @msgultekin , @mustafa-bayindir @ykw090721 
A PR from @MST1122  was merged which addresses the problem with the encryption and feed downloads.
You need to update your `duble-break/spiapi-php` installations to the new `v1.0.4` version.

Cheers
