### ISSUE TITLE
getOrders 400 Missing or invalid request parameters: [MarketplaceIds]

### ISSUE THREAD

**Issue by aniruddhaad** [double-break/spapi-php#40]
Any idea how does this thing works?
getOrders API call does not work with either array nor json as input -

Here is my code -

$credentials = new DoubleBreak\Spapi\Credentials($tokenStorage, $signer, $config);
$cred = $credentials->getCredentials();
$reportClient = new DoubleBreak\Spapi\Api\Orders($cred, $config);
try
{
  $number_of_datys=3325;
  $LastUpdatedAfter=new DateTime(date("Y-m-d",mktime(0,0,0,date("m"),date("d")-$number_of_datys,date("Y"))));
  
  
  
var_dump($reportClient->getOrders(['MarketplaceIds'=>['ATVPDKIKX0DER','A2EUQ1WTGCTBG2'],'LastUpdatedAfter'=>$LastUpdatedAfter->format('c'), 'orderStatuses'=>['Shipped']]  ));
}
catch (\GuzzleHttp\Exception\ClientException $e) {
  
    echo "\nLINE NO: ".__LINE__."\n";
    $httpCode = $e->getResponse()->getStatusCode();
    $errorBody =  $e->getResponse()->getBody();
  
    echo "Amazon SP API responded with HTTP {$httpCode}\n {$errorBody}";
    exit;
  
  } 

Also in order to satisfy amazon signature version 4 does not match error -
I fixed it by creating a function for encoding marketplace id array  square brackets using this function in client.php and replaced at line number 57 & 62 -
public function custombuildquery($params, $encoding = PHP_QUERY_RFC3986)
  {
      if (!$params) {
          return '';
      }

      if ($encoding === false) {
          $encoder = function ($str) {
              return $str;
          };
      } elseif ($encoding === PHP_QUERY_RFC3986) {
          $encoder = 'rawurlencode';
      } elseif ($encoding === PHP_QUERY_RFC1738) {
          $encoder = 'urlencode';
      } else {
          throw new \InvalidArgumentException('Invalid type');
      }

      $qs = '';
      foreach ($params as $k => $v) {
          $k = $encoder($k);
          if (!is_array($v)) {
              $qs .= $k;
              if ($v !== null) {
                  $qs .= '=' . $encoder($v);
              }
              $qs .= '&';
          } else {
              foreach ($v as $aindex=>$vv) {
                  $qs .= $k.rawurlencode('['.$aindex.']');
                  if ($vv !== null) {
                      $qs .= '=' . $encoder($vv);
                  }
                  $qs .= '&';
              }
          }
      }

      return $qs ? (string) substr($qs, 0, -1) : '';
  }

**Comment by aniruddhaad** [comment]
Here is working solution for anyone still struggling with this -
1. It seems like the marketplace ids is not literally an array anymore. If you pass array then it brakes the flow.
**You need to pass multiple marketplaces like this "ATVPDKIKX0DER,A2EUQ1WTGCTBG2"** 
so request should be like this (php code) -
$LastUpdatedAfter=gmdate("Y-m-d\TH:i:s\Z",mktime(0,0,0,date("m"),date("d"),date("Y")));
  var_dump($reportClient->getOrders(['MarketplaceIds'=>'ATVPDKIKX0DER,A2EUQ1WTGCTBG2','LastUpdatedAfter'=>$LastUpdatedAfter, 'orderStatuses'=>['Shipped']]  ));
2. As I mentioned in my previous post the \GuzzleHttp\Psr7\build_query on line 57, 62 needs to be replaced with the custom function I made in the client.php. 
**If you don't do this then you will get error -**
**"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.**

See modified client.php below
`<?php
namespace DoubleBreak\Spapi;

class Client {

  use HttpClientFactoryTrait;

  protected $credentials;
  protected $config;
  protected $signer;
  protected $lastHttpResponse = null;
  public function __construct(array $credentials = [], array $config = [])
  {
    $this->credentials = $credentials;
    $this->config = $config;
    $this->signer = new Signer(); //Should be injected :(
  }


  private function normalizeHeaders($headers)
  {
    return $result = array_combine(
       array_map(function($header) { return strtolower($header); }, array_keys($headers)),
       $headers
    );

  }

  private function headerValue($header)
  {
      return \GuzzleHttp\Psr7\Header::parse($header)[0];
  }

  public function send($uri, $requestOptions = [])
  {
    $requestOptions['headers'] = $requestOptions['headers'] ?? [];
    $requestOptions['headers']['accept'] = 'application/json';
    $requestOptions['headers'] = $this->normalizeHeaders($requestOptions['headers']);


    //Prepare for signing
    $signOptions = [
      'service' => 'execute-api',
      'access_token' => $this->credentials['access_token'],
      'access_key' => $this->credentials['sts_credentials']['access_key'],
      'secret_key' =>  $this->credentials['sts_credentials']['secret_key'],
      'security_token' =>  $this->credentials['sts_credentials']['session_token'],
      'region' =>  $this->config['region'] ?? null,
      'host' => $this->config['host'],
      'uri' =>  $uri,
      'method' => $requestOptions['method']
    ];
    
    if (isset($requestOptions['query'])) {
      $query = $requestOptions['query'];
      ksort($query);
      $signOptions['query_string'] =  $this->custombuildquery($query);
    }

    if (isset($requestOptions['form_params'])) {
      ksort($requestOptions['form_params']);
      $signOptions['payload'] = $this->custombuildquery($requestOptions['form_params']);
    }

    if (isset($requestOptions['json'])) {
      ksort($requestOptions['json']);
      $signOptions['payload'] = json_encode($requestOptions['json']);
    }

    //Sign
    $requestOptions = $this->signer->sign($requestOptions, $signOptions);

    //Prep client and send the request
    $client = $this->createHttpClient([
      'base_uri' => 'https://' . $this->config['host']
    ]);

    try {
      $this->lastHttpResponse = null;
      $method = $requestOptions['method'];
      unset($requestOptions['method']);
      $response = $client->request($method, $uri, $requestOptions);
      $this->lastHttpResponse = $response;
      return json_decode($response->getBody(), true);
    } catch (\GuzzleHttp\Exception\ClientException $e) {
      $this->lastHttpResponse = $e->getResponse();
      throw $e;
    }

  }

  public function getLastHttpResponse()
  {
    return $this->lastHttpResponse;
  }

  public function custombuildquery($params, $encoding = PHP_QUERY_RFC3986)
  {
      if (!$params) {
          return '';
      }

      if ($encoding === false) {
          $encoder = function ($str) {
              return $str;
          };
      } elseif ($encoding === PHP_QUERY_RFC3986) {
          $encoder = 'rawurlencode';
      } elseif ($encoding === PHP_QUERY_RFC1738) {
          $encoder = 'urlencode';
      } else {
          throw new \InvalidArgumentException('Invalid type');
      }

      $qs = '';
      foreach ($params as $k => $v) {
          $k = $encoder($k);
          if (!is_array($v)) {
              $qs .= $k;
              if ($v !== null) {
                  $qs .= '=' . $encoder($v);
              }
              $qs .= '&';
          } else {
              foreach ($v as $aindex=>$vv) {
                  $qs .= $k.rawurlencode('['.$aindex.']');
                  if ($vv !== null) {
                      $qs .= '=' . $encoder($vv);
                  }
                  $qs .= '&';
              }
          }
      }

      return $qs ? (string) substr($qs, 0, -1) : '';
  }

}
`
Voila issue solved. It took my days to come up with working solutions.

I don't know how to ask to merge these changes. May be some moderator or repo owner will do it on their will.

**Comment by ccarnivore** [comment]
@aniruddhaad thanks mate, you helped me alot here!

**Comment by aniruddhaad** [comment]
> @aniruddhaad thanks mate, you helped me alot here!

I am happy to know that it saved your time :-)

**Comment by lyubo-slavilov** [comment]
@aniruddhaad 

Hi there,

I am aware of this strange behavior of the library. 
It can not handle properly arrays for HTTP query parameters. This limitation is due to `GuzzleHttp\Psr7\build_query()` which is used to compose all sorts of things during the request preparation. This function serializes arrays in `expoded from` style, but 
amazon SP API requires array values to be serialized in `unexploded-simple` style (basically CSV).

So when I am dealing with arrays i just serialize the values my self:

```php
$result = $client->getSomething([
  'marketplaceIds' => 'ABCD,XYZ,ЬЮЯ`
]);
```

More on serialization styles here:
https://swagger.io/docs/specification/serialization/

### Closing thoughts
Unfortunately I cant accept your solution since it will impact all the users.
Best chance to implement this will be in  2.0.0 version someday ;)
