### ISSUE TITLE
How to keep refreshing the refresh_token?

### ISSUE THREAD

**Issue by aniruddhaad** [double-break/spapi-php#41]
It randomly gives me "unauthorized error" "The security token included in the request is expired".

I observed that, in the Credentials.php there is getLWAToken() function which does the job of refreshing the token however it returns access token only.

I am not sure if we have to manually make some calls to refresh the token or the library does that for me?

Anyone knows?

**Comment by aniruddhaad** [comment]
Ok. If anyone still having this issue. I think solution is just to truncate the temporary aws-tokens i.e. SimpleTokenStorage file.
Everytime you run the code just truncate the file. I don't think contents of this file are rechecked for if its still valid or not.
TODO: Perhaps a simple check in SimpleTokenStorage class/function would solve the issue without doing any further actions to be taken outside the class. 
Please correct me if I am wrong.

**Comment by lyubo-slavilov** [comment]
Hi there, 
I run to the same problem - will think of something and will implement it.
My situation however is a little bit special - long running proces which uses only one instance of a client

> I don't think contents of this file are rechecked for if its still valid or not.

This is not true. The file is checked whenever a fresh credentials are made

**Comment by aniruddhaad** [comment]
> Hi there, I run to the same problem - will think of something and will implement it. My situation however is a little bit special - long running proces which uses only one instance of a client
> 
> > I don't think contents of this file are rechecked for if its still valid or not.
> 
> This is not true. The file is checked whenever a fresh credentials are made

I end up creating different temporary files per user so that they don't cause problems with any other accounts as effect of multiple instance of same script running.

**Comment by lyubo-slavilov** [comment]
Well - the TokenStorage accepts configuration. The user can specify
different storage files for different workers
Kind Regards,
*Lyubomir Slavilov*
