### ISSUE TITLE
Assume Role Error

### ISSUE THREAD

**Issue by ErAmar** [double-break/spapi-php#44]
{"Error":{"Code":"AccessDenied","Message":"Roles may not be assumed by root accounts.","Type":"Sender"},"RequestId":"ed7

**Comment by ErAmar** [comment]
please guides us above error

**Comment by lyubo-slavilov** [comment]
I can help only with the code of the library.
You should follow the steps of the developer onboarding here
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by ErAmar** [comment]
thank you slavilov we have done that issue
