### ISSUE TITLE
Assume Role error

### ISSUE THREAD

**Issue by ErAmar** [double-break/spapi-php#45]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sts.amazonaws.com/` resulted in a `403 Forbidden` response: {"Error":{"Code":"AccessDenied","Message":"Roles may not be assumed by root accounts.","Type":"Sender"},"RequestId":"9db (truncated...)

**Comment by lyubo-slavilov** [comment]
It seems it is not bug in the library, but your setup seems wrong. 
I can not help with that
