### ISSUE TITLE
listingsitems

### ISSUE THREAD

**Issue by xyloneX** [double-break/spapi-php#46]
{                                                                                                                         
  "errors": [                                                                                                             
    {                                                                                                                     
      "message": "The request signature we calculated does not match the signature you provided. C (truncated...)         
)

**Comment by lyubo-slavilov** [comment]
Please provide more information.
The best ould be some formatted example code

**Comment by lyubo-slavilov** [comment]
> { "errors": [ { "message": "The request signature we calculated does not match the signature you provided. C (truncated...) )

Please provide more information.
The best ould be some formatted example code
