### ISSUE TITLE
Remove these text from from the output

### ISSUE THREAD

**Issue by ErAmar** [double-break/spapi-php#47]
* Hostname sellingpartnerapi-eu.amazon.com was found in DNS cache * Trying 34.243.126.182... * TCP_NODELAY set * Connected to sellingpartnerapi-eu.amazon.com (34.243.126.182) port 443 (#0) * ALPN, offering http/1.1 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: CN=sellingpartnerapi-eu.amazon.com * start date: Apr 4 00:00:00 2021 GMT * expire date: May 3 23:59:59 2022 GMT * issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon * SSL certificate verify ok. > GET /orders/v0/orders?MarketplaceIds=XXXXXXXXXX&OrderStatuses=Pending&CreatedAfter=2022-01-05 HTTP/1.1 host: sellingpartnerapi-eu.amazon.com accept: application/json user-agent: spapi_client x-amz-access-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-amz-date: 20220113T111857Z x-amz-security-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXX/20220113/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < HTTP/1.1 200 OK < Date: Thu, 13 Jan 2022 11:18:57 GMT < Content-Type: application/json < Content-Length: 850 < Connection: keep-alive < x-amzn-RequestId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < x-amzn-RateLimit-Limit: 0.0167 < x-amz-apigw-id: L4aZRGuMDoEF-XA= < X-Amzn-Trace-Id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < * Connection #0 to host sellingpartnerapi-eu.amazon.com left intact * Hostname sellingpartnerapi-eu.amazon.com was found in DNS cache * Trying 34.243.126.182... * TCP_NODELAY set * Connected to sellingpartnerapi-eu.amazon.com (34.243.126.182) port 443 (#0) * ALPN, offering http/1.1 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: CN=sellingpartnerapi-eu.amazon.com * start date: Apr 4 00:00:00 2021 GMT * expire date: May 3 23:59:59 2022 GMT * issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon * SSL certificate verify ok. > GET /orders/v0/orders/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/orderItems HTTP/1.1 host: sellingpartnerapi-eu.amazon.com accept: application/json user-agent: spapi_client x-amz-access-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-amz-date: 20220113T111857Z x-amz-security-token:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXX/20220113/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < HTTP/1.1 200 OK < Date: Thu, 13 Jan 2022 11:18:58 GMT < Content-Type: application/json < Content-Length: 639 < Connection: keep-alive < x-amzn-RequestId: e1e6f30f-890b-4c42-9e22-330c5da77f51 < x-amzn-RateLimit-Limit: 0.5 < x-amz-apigw-id: L4aZVHj2joEFfqw= < X-Amzn-Trace-Id: Root=1-61e00aa1-3d62f1603db51a324b3106b6 < * Connection #0 to host sellingpartnerapi-eu.amazon.com left intact

**Comment by ErAmar** [comment]
> * Hostname sellingpartnerapi-eu.amazon.com was found in DNS cache * Trying 34.243.126.182... * TCP_NODELAY set * Connected to sellingpartnerapi-eu.amazon.com (34.243.126.182) port 443 (#0) * ALPN, offering http/1.1 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: CN=sellingpartnerapi-eu.amazon.com * start date: Apr 4 00:00:00 2021 GMT * expire date: May 3 23:59:59 2022 GMT * issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon * SSL certificate verify ok. > GET /orders/v0/orders?MarketplaceIds=XXXXXXXXXX&OrderStatuses=Pending&CreatedAfter=2022-01-05 HTTP/1.1 host: sellingpartnerapi-eu.amazon.com accept: application/json user-agent: spapi_client x-amz-access-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-amz-date: 20220113T111857Z x-amz-security-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXX/20220113/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < HTTP/1.1 200 OK < Date: Thu, 13 Jan 2022 11:18:57 GMT < Content-Type: application/json < Content-Length: 850 < Connection: keep-alive < x-amzn-RequestId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < x-amzn-RateLimit-Limit: 0.0167 < x-amz-apigw-id: L4aZRGuMDoEF-XA= < X-Amzn-Trace-Id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < * Connection #0 to host sellingpartnerapi-eu.amazon.com left intact * Hostname sellingpartnerapi-eu.amazon.com was found in DNS cache * Trying 34.243.126.182... * TCP_NODELAY set * Connected to sellingpartnerapi-eu.amazon.com (34.243.126.182) port 443 (#0) * ALPN, offering http/1.1 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: CN=sellingpartnerapi-eu.amazon.com * start date: Apr 4 00:00:00 2021 GMT * expire date: May 3 23:59:59 2022 GMT * issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon * SSL certificate verify ok. > GET /orders/v0/orders/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/orderItems HTTP/1.1 host: sellingpartnerapi-eu.amazon.com accept: application/json user-agent: spapi_client x-amz-access-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-amz-date: 20220113T111857Z x-amz-security-token:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXX/20220113/eu-west-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX < HTTP/1.1 200 OK < Date: Thu, 13 Jan 2022 11:18:58 GMT < Content-Type: application/json < Content-Length: 639 < Connection: keep-alive < x-amzn-RequestId: e1e6f30f-890b-4c42-9e22-330c5da77f51 < x-amzn-RateLimit-Limit: 0.5 < x-amz-apigw-id: L4aZVHj2joEFfqw= < X-Amzn-Trace-Id: Root=1-61e00aa1-3d62f1603db51a324b3106b6 < * Connection #0 to host sellingpartnerapi-eu.amazon.com left intact

**Comment by lyubo-slavilov** [comment]
Well
```php
$config = [
    //Guzzle configuration
    'http' => [
      'verify' => false,    //<--- NOT SAFE FOR PRODUCTION
      'debug' => true       //<--- NOT SAFE FOR PRODUCTION
    ],
```
You should turn **on** http verification and turn **off** the debug mode for PROD
