### ISSUE TITLE
Get Report GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING (getReportDocument )

### ISSUE THREAD

**Issue by fruch17** [double-break/spapi-php#53]
Hello, I need help.

I'm trying to get a report (GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING) using the function  getReportDocument , but the api return this error : 
"errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
and when we add the path : /reports/2021-06-30/reports, the api return this error : 
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid or unsupported document ID found",
      "details": ""
    }
  ]
}

Here are all our app authorization : https://prnt.sc/SR840DY3LRt1 

- Selling Partner Insights  
- Amazon Fulfillment  
- Pricing  
- Finance and Accounting  
- Product Listing  
- Inventory and Order Tracking  
- Direct-to-Consumer Shipping  
- Tax Remittance  
- Tax Invoicing  

This is our code to call the function getRdtCredentials : 

$cred = $credentials->getRdtCredentials([
'restrictedResources' => [
	[
			'method' => 'GET',
			'path' => '/orders/v0/orders'
	],
	[
			'method' => 'GET',
			'path' => '/orders/v0/orders/{orderId}/orderItems'
	],
	[
			'method' => 'GET',
			'path' => '/orders/v0/orders/{orderId}/address'
	],
	[
			'method' => 'GET',
			'path' => '/orders/v0/orders/{orderId}/buyerInfo'
	],
	// [
	// 	'method' => 'GET',
	// 	'path' => '/reports/2021-06-30/reports'
	//   ]
		]
]);

$request = new Reports($cred, $config);
$reportDocumentId = $params['reportDocumentId'];
$reports = $request->getReportDocument($reportDocumentId)

I really appreciate your help

Thank you.

**Comment by lyubo-slavilov** [comment]
It seems this report is part of the Restricted Data APis, so you need to exchange your access token for an RDT token (if your developer account is approved for that)
You can check the README section about working with Restricted APIs and  RDT
https://github.com/double-break/spapi-php#working-with-restricted-data-apis
