### ISSUE TITLE
[BUG] About the size of Amazon cargo box `POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO`

### ISSUE THREAD

**Issue by AisxLee** [double-break/spapi-php#54]
I have some questions about SP-API uploading carton information:

1. Does the box size have to be uploaded? If you don't upload the box size `POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO`, but only upload the contents of the box `POST_FBA_INBOUND_CARTON_CONTENTS`, will Amazon charge extra because it doesn't have the box size?
2. `POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO` is uploading still `workflow for submitting a feed`?
3. I use `Feeds API v2020-09-04`,
When calling the `createFeedDocument` interface, the corresponding `contentType` value is `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8`.
When calling the `createFeed` interface, the corresponding `feedType` value is `POST_FLAT_FILE_FROM_EXCEL_FBA_CREATE_CARTON_INFO`.
However, the information returned by calling the `getFeedDocument` interface is `The file format is invalid. The Excel pack list should be uploaded as a .xlsx file.`
I tried. Windows creates a new xlsx, generates xlsx with PHP, `contentType` is replaced by `application/vnd.ms-excel; charset=UTF-8`, blank excel, etc., but the information returned by `getFeedDocument` remains unchanged...

I'm almost depressed!
@lyubo-slavilov

**Comment by lyubo-slavilov** [comment]
Hello there,
I am author of the SP API client, and not the author of the API itself.

It seems you have to check Amazon's documentation to look for your answers,
since I do not have experience with this particular operations.

I am sorry I can't be more helpful.

Will be glad if you share your findings with us.

**Comment by lyubo-slavilov** [comment]
If you think there is a bug with the code of this library, please provide
more information about expected and actual data transfer between the client
and the API

**Comment by lyubo-slavilov** [comment]
Closed due to reporter inactivity
