### ISSUE TITLE
Data decryption

### ISSUE THREAD

**Issue by JasonYe88** [double-break/spapi-php#8]
The data returned when I request Amazon is encrypted, how should I decrypt the data? Thank you for your guidance

**Comment by MST1122** [comment]
hi @yexueping,

I have just make a commit to the master repository with Feed Upload, Download, Encryption, and Decryption all functionalities are implemented. 

It just needs an approving review from @lyubo-slavilov to be available to everyone.

**Comment by JasonYe88** [comment]
thank you very much

**Comment by JasonYe88** [comment]
I want to request getReports method,but The return value needs to be decrypted, can the decryption be encapsulated?

**Comment by MST1122** [comment]
@yexueping yes, your required functionality is also implemented under Feed->downloadFeedProcessingReport() function. it will download the report and decrypt it.

**Comment by lyubo-slavilov** [comment]
Hi guys,
First of all let me say thanks to @MST1122 for cracking this. 
The code is perfectly fine, but we need to make some refactoring in order it to fit the aerogeneration process used to generate the clients.
Me and @MST1122 already had  Google Meet call and discussed the details. So ETA end of the day we could have new version for the client ;)

Thanks again.

**Comment by JasonYe88** [comment]
@MST1122  thank you very much

**Comment by lyubo-slavilov** [comment]
@JasonYe88 PR is merged. New composer version v1.0.4 is released.
